Card Ui and Functionality
bftawfik/doc-manager pull request #22
Opened 2024-02-21 12:20 UTC by fadyfawzydev

2024-02-21 15:49 UTC, saraEid77 requested changes

2024-02-21 15:49 UTC, saraEid77 commented on src/app/_components/assignedUsers/AssignedUsers.tsx
> +              }}
why do you use style here instead of class binding?

2024-02-21 15:49 UTC, saraEid77 commented on src/app/_components/typeImage/TypeImage.tsx
> +  };
![image](https://github.com/bftawfik/doc-manager/assets/65139412/56259b66-681c-4d2a-9185-67cc0f068485)
check this to enhance the code of switch ( clean code principles )

2024-02-21 15:49 UTC, saraEid77 commented on src/app/_services/deleteFiles.ts
> +  const url = `http://localhost:3000/api/files?id=${idToUpdate}`;
Does this work on the server? 
i think we should use env variables here

2024-02-22 09:06 UTC, fadyfawzydev commented on src/app/_components/assignedUsers/AssignedUsers.tsx
> +              }}
In Tailwind you can't use dynamically binding so I approved with Bishoy to make it as style

2024-02-22 09:07 UTC, fadyfawzydev commented on src/app/_components/assignedUsers/AssignedUsers.tsx
> +          >
okay

2024-02-22 10:30 UTC, saraEid77 approved these changes

2024-02-22 10:56 UTC, merged